# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfigSettingForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Image.Image

class Ui_configSetting(object):
    def setupUi(self, configSetting):
        configSetting.setObjectName("configSetting")
        configSetting.resize(800, 600)
        configSetting.setMinimumSize(QtCore.QSize(800, 600))
        configSetting.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/LD.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        configSetting.setWindowIcon(icon)
        configSetting.setStyleSheet("QWidget{\n"
"    border-radius:20px;\n"
"    border-width: 5px;\n"
"}")
        self.label = QtWidgets.QLabel(configSetting)
        self.label.setGeometry(QtCore.QRect(180, 70, 431, 91))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(configSetting)
        self.label_2.setGeometry(QtCore.QRect(50, 170, 700, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.inputExcle = QtWidgets.QPushButton(configSetting)
        self.inputExcle.setGeometry(QtCore.QRect(300, 260, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.inputExcle.setFont(font)
        self.inputExcle.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"    border-style :ridge;\n"
"}")
        self.inputExcle.setObjectName("inputExcle")
        self.outputExcle = QtWidgets.QPushButton(configSetting)
        self.outputExcle.setGeometry(QtCore.QRect(300, 330, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.outputExcle.setFont(font)
        self.outputExcle.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"    border-style :ridge;\n"
"}")
        self.outputExcle.setObjectName("outputExcle")
        self.copy = QtWidgets.QPushButton(configSetting)
        self.copy.setGeometry(QtCore.QRect(300, 470, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.copy.setFont(font)
        self.copy.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"    border-style :ridge;\n"
"}")
        self.copy.setObjectName("copy")
        self.backBtn = QtWidgets.QPushButton(configSetting)
        self.backBtn.setGeometry(QtCore.QRect(20, 20, 75, 30))
        self.backBtn.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"    border-width: 5px;    \n"
"    border-radius:10px;\n"
"}")
        self.backBtn.setObjectName("backBtn")
        self.origin = QtWidgets.QPushButton(configSetting)
        self.origin.setGeometry(QtCore.QRect(300, 400, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.origin.setFont(font)
        self.origin.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"    border-style :ridge;\n"
"}")
        self.origin.setObjectName("origin")

        self.retranslateUi(configSetting)
        QtCore.QMetaObject.connectSlotsByName(configSetting)

    def retranslateUi(self, configSetting):
        _translate = QtCore.QCoreApplication.translate
        configSetting.setWindowTitle(_translate("configSetting", "成语竞猜-设置"))
        self.label.setText(_translate("configSetting", "设置"))
        self.label_2.setText(_translate("configSetting", "该系统通过Excle表格进行编辑，详情请复制教程查看"))
        self.inputExcle.setText(_translate("configSetting", "导入文件"))
        self.outputExcle.setText(_translate("configSetting", "导出文件"))
        self.copy.setText(_translate("configSetting", "复制链接"))
        self.backBtn.setText(_translate("configSetting", "返回"))
        self.origin.setText(_translate("configSetting", "恢复初始"))
