# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfigForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Image.Image

class Ui_config(object):
    def setupUi(self, config):
        config.setObjectName("config")
        config.resize(800, 600)
        config.setMinimumSize(QtCore.QSize(800, 600))
        config.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/LD.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        config.setWindowIcon(icon)
        config.setStyleSheet("QWidget{\n"
"    border-radius:20px;\n"
"    border-width: 5px;\n"
"}")
        self.label = QtWidgets.QLabel(config)
        self.label.setGeometry(QtCore.QRect(100, 140, 600, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(config)
        self.lineEdit.setGeometry(QtCore.QRect(150, 280, 500, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-style :ridge;")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.confirm = QtWidgets.QPushButton(config)
        self.confirm.setGeometry(QtCore.QRect(300, 390, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.confirm.setFont(font)
        self.confirm.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"    border-style :ridge;\n"
"}")
        self.confirm.setObjectName("confirm")
        self.backBtn = QtWidgets.QPushButton(config)
        self.backBtn.setGeometry(QtCore.QRect(20, 20, 75, 30))
        self.backBtn.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"    border-width: 5px;    \n"
"    border-radius:10px;\n"
"}")
        self.backBtn.setObjectName("backBtn")

        self.retranslateUi(config)
        QtCore.QMetaObject.connectSlotsByName(config)

    def retranslateUi(self, config):
        _translate = QtCore.QCoreApplication.translate
        config.setWindowTitle(_translate("config", "成语竞猜-管理员秘钥登录"))
        self.label.setText(_translate("config", "请输入管理员秘钥"))
        self.confirm.setText(_translate("config", "确认"))
        self.backBtn.setText(_translate("config", "返回"))

