# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectStartForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectStart(object):
    def setupUi(self, SelectStart):
        SelectStart.setObjectName("SelectStart")
        SelectStart.resize(800, 599)
        SelectStart.setMinimumSize(QtCore.QSize(800, 599))
        SelectStart.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/LD.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SelectStart.setWindowIcon(icon)
        SelectStart.setStyleSheet("QWidget{\n"
"    border-radius:20px;\n"
"    border-width: 5px;\n"
"}")
        self.label = QtWidgets.QLabel(SelectStart)
        self.label.setGeometry(QtCore.QRect(185, 60, 430, 90))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.startBtn = QtWidgets.QPushButton(SelectStart)
        self.startBtn.setGeometry(QtCore.QRect(460, 380, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.startBtn.setFont(font)
        self.startBtn.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"    border-style :ridge;\n"
"}")
        self.startBtn.setObjectName("startBtn")
        self.timeBox = QtWidgets.QSpinBox(SelectStart)
        self.timeBox.setGeometry(QtCore.QRect(500, 250, 151, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.timeBox.setFont(font)
        self.timeBox.setStyleSheet("QSpinBox\n"
"{\n"
"    border-style :ridge;\n"
"}")
        self.timeBox.setSuffix("")
        self.timeBox.setPrefix("")
        self.timeBox.setMaximum(100000)
        self.timeBox.setProperty("value", 120)
        self.timeBox.setObjectName("timeBox")
        self.label_2 = QtWidgets.QLabel(SelectStart)
        self.label_2.setGeometry(QtCore.QRect(430, 250, 61, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(SelectStart)
        self.radioButton.setGeometry(QtCore.QRect(160, 530, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.listView = QtWidgets.QListView(SelectStart)
        self.listView.setGeometry(QtCore.QRect(150, 190, 211, 331))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.listView.setFont(font)
        self.listView.setAutoFillBackground(False)
        self.listView.setStyleSheet("QListView\n"
"{\n"
"    border-style :ridge;\n"
"}")
        self.listView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listView.setAutoScrollMargin(100)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setDragEnabled(False)
        self.listView.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listView.setAlternatingRowColors(True)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listView.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.listView.setObjectName("listView")
        self.label_3 = QtWidgets.QLabel(SelectStart)
        self.label_3.setGeometry(QtCore.QRect(660, 250, 31, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.backBtn = QtWidgets.QPushButton(SelectStart)
        self.backBtn.setGeometry(QtCore.QRect(20, 20, 75, 30))
        self.backBtn.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"    border-width: 5px;    \n"
"    border-radius:10px;\n"
"}")
        self.backBtn.setObjectName("backBtn")

        self.retranslateUi(SelectStart)
        QtCore.QMetaObject.connectSlotsByName(SelectStart)

    def retranslateUi(self, SelectStart):
        _translate = QtCore.QCoreApplication.translate
        SelectStart.setWindowTitle(_translate("SelectStart", "成语竞猜-菜单"))
        self.label.setText(_translate("SelectStart", "菜单"))
        self.startBtn.setText(_translate("SelectStart", "开始"))
        self.label_2.setText(_translate("SelectStart", "时间"))
        self.radioButton.setText(_translate("SelectStart", "全选"))
        self.label_3.setText(_translate("SelectStart", "秒"))
        self.backBtn.setText(_translate("SelectStart", "返回"))
import Image.Image
