# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WelcomeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Image.Image


class Ui_welcomeForm(object):
    def setupUi(self, welcomeForm):
        welcomeForm.setObjectName("welcomeForm")
        welcomeForm.resize(800, 600)
        welcomeForm.setMinimumSize(QtCore.QSize(800, 600))
        welcomeForm.setMaximumSize(QtCore.QSize(1200, 800))
        welcomeForm.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/LD.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        welcomeForm.setWindowIcon(icon)
        welcomeForm.setStyleSheet("QWidget{\n"
"    border-radius:20px;\n"
"    border-width: 5px;\n"
"}")
        self.Words = QtWidgets.QLabel(welcomeForm)
        self.Words.setGeometry(QtCore.QRect(0, 50, 800, 200))
        font = QtGui.QFont()
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.Words.setFont(font)
        self.Words.setAlignment(QtCore.Qt.AlignCenter)
        self.Words.setObjectName("Words")
        self.start = QtWidgets.QPushButton(welcomeForm)
        self.start.setGeometry(QtCore.QRect(250, 300, 300, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.start.setFont(font)
        self.start.setFocusPolicy(QtCore.Qt.NoFocus)
        self.start.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.start.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.start.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"    border-width: 5px;\n"
"border-style :ridge;\n"
"}")
        self.start.setIconSize(QtCore.QSize(300, 71))
        self.start.setCheckable(False)
        self.start.setObjectName("start")
        self.config = QtWidgets.QPushButton(welcomeForm)
        self.config.setGeometry(QtCore.QRect(250, 410, 300, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.config.setFont(font)
        self.config.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"border-style :ridge;\n"
"}")
        self.config.setObjectName("config")
        self.about = QtWidgets.QPushButton(welcomeForm)
        self.about.setGeometry(QtCore.QRect(670, 540, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.about.setFont(font)
        self.about.setStyleSheet("QPushButton:hover\n"
"{\n"
"\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.493818, fy:0.511, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(221, 255, 253, 255))\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.494, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));\n"
"border-style :ridge;\n"
"}")
        self.about.setObjectName("about")

        self.retranslateUi(welcomeForm)
        QtCore.QMetaObject.connectSlotsByName(welcomeForm)

    def retranslateUi(self, welcomeForm):
        _translate = QtCore.QCoreApplication.translate
        welcomeForm.setWindowTitle(_translate("welcomeForm", "成语竞猜"))
        self.Words.setText(_translate("welcomeForm", "成语竞猜"))
        self.start.setText(_translate("welcomeForm", "开始"))
        self.config.setText(_translate("welcomeForm", "设置"))
        self.about.setText(_translate("welcomeForm", "关于"))
